# Generated by Django 4.0.7 on 2024-04-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_alter_actor_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=170, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='url',
            field=models.SlugField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default='', max_length=180, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='moviepicture',
            name='title',
            field=models.CharField(max_length=180, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ip',
            field=models.CharField(max_length=25, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
    ]
